[project]
name = "pymc-gpx"
channels = ["conda-forge"]
platforms = ["linux-64"]

[pypi-dependencies]
pymc-gpx = { path = ".", editable = true }

[dependencies]
pymc = "*"

[feature.dev.dependencies]
ipython = "*"
ipykernel = "*"
mypy = "*"
pandas-stubs = "*"
pip = "*"
pre-commit = "*"
pytest = "*"
python-build = "*"
ruff = "*"
taplo = "*"

[feature.dev.tasks]
test = "pytest --ignore tests/old"
test-old = "pytest tests/old"
mypy = "mypy"

[environments]
default = ["dev"] # Default environment is default feature plus dev feature
prod = []         # Just the default feature
