name: Build and maybe release to PyPI

on:
  push:
    branches: [main]
    tags: ['*']
  release:
    types:
    - published
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: hynek/build-and-inspect-python-package@v2
      with:
        attest-build-provenance-github: 'true'
  publish:
    if: github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build
    # Run this job in an isolated GHA environment containing the OIDC credentials.
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.10.0
